eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  register-with-eureka: false
  fetch-registry: false
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost
  server:
    peer-node-read-timeout-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'