eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: '1.0'

      
server:
  peer-node-read-timeout-ms: '5000'
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/
  tracing:
    sampling:
      probability: '1.0'
        
logging:
  file:
    name: ${java.io.tmpdir}/logs/${spring.application.name}.log
  level:
    root: error
