spring:
  datasource:
    continue-on-error: true
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres?ApplicationName=${spring.application.name}
    username: postgres
    password: 1234
    
server:
  error:
    include-stacktrace: always

    
logging:
  level:
    root: trace
