spring:
  datasource:
    continue-on-error: true
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres?ApplicationName=${spring.application.name}
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    
server:
  error:
    include-stacktrace: always

logging:
  file:
    name: ${java.io.tmpdir}/logs/${spring.application.name}.log
  level:
    root: info
