spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    
server:
  error:
    include-stacktrace: always

logging:
  file:
    name: ${java.io.tmpdir}/logs/${spring.application.name}.log
  level:
    root: debug
