eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
server:
  peer-node-read-timeout-ms: '5000'
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  file:
    name: ${java.io.tmpdir}/logs/${spring.application.name}.log
  level:
    root: error
